"""数据库方言适配层的单元测试（纯逻辑，不需要真实数据库）。

由 ``src/model/database.py`` 承担的双数据库适配是整个"永久部署"方案的地基，
因此这里把最容易出错的两处单独拿出来测：

* ``translate_placeholders``：``?`` -> ``%s`` 的翻译必须跳过字符串字面量，
  并且要正确转义 ``%``；
* ``resolve_database_target`` / ``Config.dialect``：数据库选择的判定规则。

真实连接层面则由 ``tests/test_api.py`` 覆盖——它既能跑 SQLite，
也能通过环境变量 ``CALC_TEST_DATABASE_URL`` 跑在真实 PostgreSQL 上。

运行方式::

    python -m unittest tests.test_database_dialect -v
"""

import sys
import unittest
from pathlib import Path
from unittest import mock

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import (  # noqa: E402
    DIALECT_POSTGRESQL,
    DIALECT_SQLITE,
    Config,
)
from src.model.database import (  # noqa: E402
    SCHEMA_FILE,
    SCHEMA_FILE_POSTGRES,
    resolve_database_target,
    schema_path_for,
    split_sql_statements,
    translate_placeholders,
)


class TranslatePlaceholdersTests(unittest.TestCase):
    """占位符翻译。"""

    def test_single_placeholder(self):
        self.assertEqual(
            translate_placeholders("SELECT * FROM t WHERE a = ?"),
            "SELECT * FROM t WHERE a = %s",
        )

    def test_multiple_placeholders(self):
        self.assertEqual(
            translate_placeholders("INSERT INTO t (a, b) VALUES (?, ?)"),
            "INSERT INTO t (a, b) VALUES (%s, %s)",
        )

    def test_question_mark_inside_string_literal_is_kept(self):
        self.assertEqual(
            translate_placeholders("SELECT * FROM t WHERE a = 'x?y' AND b = ?"),
            "SELECT * FROM t WHERE a = 'x?y' AND b = %s",
        )

    def test_escaped_quote_inside_literal(self):
        """SQL 里两个连续单引号表示一个单引号，不能提前把字面量闭合。"""
        self.assertEqual(
            translate_placeholders("SELECT 'it''s ?' AS s, ? AS v"),
            "SELECT 'it''s ?' AS s, %s AS v",
        )

    def test_percent_is_escaped_for_psycopg(self):
        """psycopg 用 % 作为参数标记，字面量里的 % 必须写成 %%。"""
        self.assertEqual(
            translate_placeholders("SELECT * FROM t WHERE a LIKE '50%'"),
            "SELECT * FROM t WHERE a LIKE '50%%'",
        )

    def test_double_quoted_identifier_is_skipped(self):
        self.assertEqual(
            translate_placeholders('SELECT "weird?name" FROM t WHERE a = ?'),
            'SELECT "weird?name" FROM t WHERE a = %s',
        )

    def test_real_query_from_repository(self):
        """取自 DAO 的真实语句：LIKE 用参数传入，SQL 文本里不含 %。"""
        sql = "(expression LIKE ? OR result LIKE ?)"
        self.assertEqual(
            translate_placeholders(sql), "(expression LIKE %s OR result LIKE %s)"
        )


class SplitSqlStatementsTests(unittest.TestCase):
    """建表脚本切分。"""

    def test_comments_and_empty_statements_are_dropped(self):
        script = (
            "-- 这是注释\n"
            "CREATE TABLE a (id INTEGER);\n"
            "\n"
            "-- 又一条注释\n"
            "CREATE INDEX i ON a (id);\n"
        )
        statements = split_sql_statements(script)
        self.assertEqual(len(statements), 2)
        self.assertTrue(statements[0].startswith("CREATE TABLE"))
        self.assertTrue(statements[1].startswith("CREATE INDEX"))

    def test_real_schema_files_are_parsable(self):
        for path in (SCHEMA_FILE, SCHEMA_FILE_POSTGRES):
            with self.subTest(schema=path.name):
                statements = split_sql_statements(path.read_text(encoding="utf-8"))
                # 应该有：建表 + 两个索引
                self.assertEqual(len(statements), 3)
                self.assertIn("calculation_history", statements[0])
                self.assertEqual(len([s for s in statements if s.startswith("CREATE INDEX")]), 2)


class SchemaSelectionTests(unittest.TestCase):
    """建表脚本选择。"""

    def test_sqlite_schema(self):
        self.assertEqual(schema_path_for(DIALECT_SQLITE), SCHEMA_FILE)
        self.assertTrue(schema_path_for(DIALECT_SQLITE).exists())

    def test_postgres_schema(self):
        self.assertEqual(schema_path_for(DIALECT_POSTGRESQL), SCHEMA_FILE_POSTGRES)
        text = SCHEMA_FILE_POSTGRES.read_text(encoding="utf-8")
        # 只检查真正会被执行的 DDL（文件头注释里会提到 AUTOINCREMENT 用于对比说明）
        create_table = split_sql_statements(text)[0]
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", create_table)
        self.assertNotIn("AUTOINCREMENT", create_table)


class ResolveDatabaseTargetTests(unittest.TestCase):
    """数据库选择规则。"""

    def test_explicit_path_forces_sqlite(self):
        dialect, target = resolve_database_target(database_path="/tmp/a.db")
        self.assertEqual(dialect, DIALECT_SQLITE)
        self.assertEqual(target, "/tmp/a.db")

    def test_explicit_url_forces_postgresql(self):
        url = "postgresql://user:pw@host:5432/db"
        dialect, target = resolve_database_target(database_url=url)
        self.assertEqual(dialect, DIALECT_POSTGRESQL)
        self.assertEqual(target, url)

    def test_defaults_to_sqlite_without_database_url(self):
        with mock.patch.dict("os.environ", {"DATABASE_URL": ""}, clear=False):
            dialect, target = resolve_database_target()
        self.assertEqual(dialect, DIALECT_SQLITE)
        self.assertTrue(str(target).endswith("calculator.db"))


class ConfigDialectTests(unittest.TestCase):
    """配置对象对数据库类型的判断。"""

    def test_sqlite_by_default(self):
        config = Config()
        self.assertEqual(config.dialect, DIALECT_SQLITE)
        self.assertIsNone(config.normalized_database_url)

    def test_postgres_scheme_is_normalized(self):
        """Render/Heroku 给的 postgres:// 必须转成 psycopg 认识的 postgresql://"""
        config = Config(database_url="postgres://user:pw@host:5432/db")
        self.assertEqual(config.dialect, DIALECT_POSTGRESQL)
        self.assertTrue(config.normalized_database_url.startswith("postgresql://"))

    def test_database_uri_hides_password(self):
        config = Config(database_url="postgresql://user:secret@host:5432/db")
        self.assertNotIn("secret", config.database_uri)
        self.assertIn("host", config.database_uri)

    def test_sqlite_uri_is_the_file_path(self):
        config = Config(database_path="/tmp/x.db")
        self.assertEqual(config.database_uri, "/tmp/x.db")


if __name__ == "__main__":
    unittest.main(verbosity=2)
