-- ---------------------------------------------------------------------------
-- 计算器系统数据库表结构（PostgreSQL 版本）
-- 作者：832402204 陈俊洁
--
-- 与 sqlite 版本的差别只有自增主键的写法：
--   SQLite     : INTEGER PRIMARY KEY AUTOINCREMENT
--   PostgreSQL : INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
-- 其余字段、索引与含义完全一致，业务代码不需要区分。
--
-- 该文件由 src/model/database.py 在检测到 DATABASE_URL 时自动执行；
-- 也可以在部署平台上手动执行（例如 Neon 控制台的 SQL Editor）。
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS calculation_history (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expression  TEXT    NOT NULL,                           -- 归一化后的计算表达式
    result      TEXT    NOT NULL,                           -- 计算结果（高精度文本）
    created_at  TEXT    NOT NULL,                           -- 计算时间 YYYY-MM-DD HH:MM:SS
    is_favorite INTEGER NOT NULL DEFAULT 0                  -- 是否收藏：0 否 / 1 是
);

CREATE INDEX IF NOT EXISTS idx_history_created_at
    ON calculation_history (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_history_is_favorite
    ON calculation_history (is_favorite);
